version: '3'
services:
  weby:
    build:
      context: .
    command: sh -c 'python manage.py makemigrations && python manage.py migrate && exec gunicorn pro.wsgi:application --workers=4 --bind 0.0.0.0:8000'
   
    ports:
      - '8000:8000'
